version: '3.7'
services:
  spark-master:
    image: quay.io/comp-bio-aging/spark-master:master
    user: "spark"
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
    - 8080:8080
    - 7077:7077
    - 6066:6066
    env_file:
    - conf/bigdata.env
    volumes:
    - ./conf/spark/spark.conf:/spark/conf/spark-defaults.conf
    - /data:/data
  spark-worker:
    image: quay.io/comp-bio-aging/spark-worker:master
    user: "spark"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
    - 8081:8081
    - 8082:8082
    - 8083:8083
    - 7337:7337
    env_file:
    - conf/bigdata.env
    volumes:
    - ./conf/spark/spark.conf:/spark/conf/spark-defaults.conf
    - /data:/data
  zeppelin:
    image: quay.io/comp-bio-aging/zeppelin:master
    user: "zeppelin"
    env_file:
    - conf/bigdata.env
    ports:
    - 9002:8080
    - 4040:4040
    - 4041:4041
    - 4042:4042
    volumes:
    - /data/notebooks/zeppelin:/zeppelin/notebook
    #- ./conf/alluxio/alluxio-1.8.0-client.jar:/zeppelin/local-repo/org/alluxio/alluxio-core-client/1.8.0/alluxio-1.8.0-client.jar
    - /data:/data
    - ./conf/zeppelin/conf:/zeppelin/conf
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
  db:
    image: postgres:10.5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/databases/postgres
    volumes:
    - ./conf/geometa/init/sequencing.sql:/docker-entrypoint-initdb.d/sequencing.sql
    - /data/databases/postgres:/data/databases/postgres
    ports:
    - 5432:5432
  adminer:
    image: adminer:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - 5050:8080
  # DataStax Enterprise
#  dse:
#    image: datastax/dse-server:latest
#    command: [ -s ]
#    ports:
#      - "9042:9042" # cassandra
#    environment:
#      DS_LICENSE: accept
#    env_file:
#      - conf/bigdata.env
#    volumes:
#      - "/data/databases/cassandra:/var/lib/cassandra"
  # One instance of DataStax Studio
#  studio:
#    image: datastax/dse-studio:latest
#    ports:
#      # The Web UI exposed to our host
#      - "9091:9091"
#    depends_on:
#      - dse
#    environment:
#      DS_LICENSE: accept
#    env_file:
#      - conf/bigdata.env
#    #note: nonroot container, so volume should be 777 or similar
#    volumes:
#      - "/data/notebooks/datastax:/var/lib/datastax-studio"
#  graphdb:
#    image: ontotext/graphdb:8.10.1-se
#    ports:
#      - "7200:7200"
#    volumes:
#      - "/data/databases/graphdb:/opt/graphdb/home"
#    env_file:
#      - conf/bigdata.env

networks:
  default:
    driver: overlay
    attachable: true
