version: '3.4'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
      - /pipelines:/pipelines
    environment:
      - CLUSTER_NAME=gerontomics
    env_file:
      - conf/bigdata.env
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 50070:50070
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
      - /pipelines:/pipelines
    env_file:
      - conf/bigdata.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  spark-master:
    image: bde2020/spark-master:2.3.1-hadoop2.7
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
    env_file:
      - conf/bigdata.env
    volumes:
      - ./conf/spark/spark.conf:/spark/conf/spark-defaults.conf
      - /pipelines:/pipelines
  spark-worker:
    image: quay.io/comp-bio-aging/spark-worker:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    env_file:
      - conf/bigdata.env
    volumes:
      - ./conf/spark/spark.conf:/spark/conf/spark-defaults.conf
      - /pipelines:/pipelines
  jupyter:
    image: quay.io/comp-bio-aging/spark-ml-notebook
    env_file:
      - conf/bigdata.env
    ports:
      - 9001:8888
    volumes:
         - ./notebooks/jupyter:/home/jovyan/
         - /pipelines:/pipelines
    command: start.sh jupyter lab
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager
  zeppelin:
    image: quay.io/comp-bio-aging/zeppelin
    env_file:
      - conf/bigdata.env
    ports:
      - 9002:8080
    volumes:
         - ./notebooks/zeppelin/notebook:/zeppelin/notebook
         - ./notebooks/zeppelin/logs:/zeppelin/logs
         - /pipelines:/pipelines
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure

  cromwell-client:
    image: quay.io/comp-bio-aging/cromwell-web:0.0.13
    env_file:
      - conf/bigdata.env
    ports:
      - 8001:8080
    volumes:
         - /pipelines:/pipelines
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
  # HUE STUFF
  hue:
    image: gethue/hue:latest
    ports:
      - 8888:8888
    volumes:
      - ./conf/hue/hue.ini:/hue/desktop/conf/pseudo-distributed.ini
    deploy:
        replicas: 1
        mode: replicated
        restart_policy:
          condition: on-failure

volumes:
  datanode:
  namenode:

networks:
  default:
    driver: overlay
    attachable: true
